### ISSUE TITLE
problem with seeing gameobjects outside of fov

### ISSUE THREAD

**Issue by pulpxi** [EntroPi-Games/GPU-Line-of-Sight#2]

**Comment by EntroPiGames** [comment]
Are you talking about the npc character just outside the line of sight?

What kind of mesh is used to draw the sprite? The mesh might be intersecting the LOS source camera's frustum, while the texture only covers a part of the mesh.

**Comment by pulpxi** [comment]
It isnt using any mesh, its just a sprite but i already tried putting a mesh with the sprite and the same result came out:
I enabled the mesh and the mesh is doing well:
![Screenshot_3](https://user-images.githubusercontent.com/78758377/107275182-b2d30080-6a51-11eb-9d12-6b3fe4d489c3.png)
![Screenshot_4](https://user-images.githubusercontent.com/78758377/107275189-b49cc400-6a51-11eb-8731-1366aa56c5e1.png)
but not the sprite, it apears to early:
![Screenshot_5](https://user-images.githubusercontent.com/78758377/107275216-bebec280-6a51-11eb-87a5-943dd940d5d7.png)

**Comment by EntroPiGames** [comment]
A _Sprite Renderer_ component will also use a mesh internally to draw the sprite to the screen. 

If you set the Scene view draw mode to _Shaded Wireframe_ you should be able to see the mesh that's being used to draw the NPC sprite.

![image](https://user-images.githubusercontent.com/45169553/107281164-9cc93e00-6a59-11eb-8ed3-8029b43e8d8d.png)

**Comment by pulpxi** [comment]
yes, it looks like this:
![Screenshot_6](https://user-images.githubusercontent.com/78758377/107287401-3268cb80-6a62-11eb-821a-dc294a4f2525.png)

**Comment by pulpxi** [comment]
can i change it(size  maybe...) in any way ?

**Comment by pulpxi** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/78758377/107287541-5f1ce300-6a62-11eb-9de6-80886f770db3.png)
it doesent seem to be the problem i guess because the fov is still far from the mesh...

**Comment by EntroPiGames** [comment]
The _LOS Culler_ component uses the mesh's [Axis Aligned Bounding Box](https://docs.unity3d.com/ScriptReference/Bounds.html) (AABB) to [calculate the visibility of the mesh](https://github.com/EntroPi-Games/GPU-Line-of-Sight/blob/a39027dca43c31a7e0b24de5a9a50543d8726d55/Assets/EntroPi/GPU%20Line%20Of%20Sight/Scripts/LOSCuller.cs#L47).

Because the mesh generated from the sprite has some artifacts, the AABB is larger than the sprite itself and does intersect with the line of sight:

![image](https://user-images.githubusercontent.com/45169553/107353972-eb182480-6acd-11eb-9f93-24d9912fd34f.png)

The best fix would be to clean up the sprite image, so that the generated mesh is cleaner and fits the sprite perfectly.

**Comment by pulpxi** [comment]
this is really interesting i didnt know that.
What you mean by cleaning the sprite?

**Comment by pulpxi** [comment]
i mage a png just of pixels:
![Screenshot_11](https://user-images.githubusercontent.com/78758377/107358589-dccd0700-6ad3-11eb-9527-1d861e3938ca.png)
but i still have these edges...

**Comment by EntroPiGames** [comment]
My guess is that the NPC sprite contains a couple of pixels which aren't completely transparent, so you might need to fix that in an image editor.

You could also try setting the Mesh Type for the texture to _Full Rect_ instead of _Tight_.

But the topic of sprite mesh generation is no longer related to this asset, so might be better to ask on the Unity forum instead.

**Comment by pulpxi** [comment]
ok i will but you helped me alot. i thank you so much <33333
